config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  resources :articles
  resources :users

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get "/homes/userule", to: "homes#userule"
  get "/homes/privacy", to: "homes#privacy"
  # get "/profile/index", to: "profile#index"
  # post "articles/:id/update" => "articles#update"
  # get "/articles/new", to: "articles#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, presence: true
  validates :body, presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  
  def index
    @article = Article.order(created_at: :desc).all
  end

  def show
    @article = Article.find(params[:id])
    @user = User.find(@article.user_id)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def new
    # 空のメソッドを作成
    @article = Article.new
  end

  def create
    # 空メソッドに、データを入れ、saveでDBに保存
    @article = Article.new(params.require(:article).permit(:title, :body, :image).merge(user_id: current_user.id))
    # @article.save
    if @article.save
      redirect_to @article, notice: "作成できました"
    else
      render :new, alert: "作成できませんでした"
    end
  end

  def destroy
    @article = Article.find(params[:id]).destroy
    redirect_to @article
  end

  def update
    @article = find_article
    @article.update(params.require(:article).permit(:title, :body, :image))
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :image)
  end

  def find_article
    @article = Article.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<% content_for :title do %>
  MCraft｜<%= @article.title %>の編集
<% end %>
<div class="container">
  <h1 class="text-center margin-top-bottom-form">募集内容を変更する</h1>
  <%= form_for @article do |f| %>

    <div class="form-group padding-top-15">
      <% if @article.image? %>
        <%= image_tag @article.image.url, class: "img-fluid" %>
      <% else %>
        <%= image_tag "need/default.png"%>
      <% end %>
      <%= f.file_field :image %>
      <p>※選択しても表示されている画像は変わりませんが投稿すると、表示されます。</p>
    </div>
    <div class="form-group padding-top-15">
      <%= f.label(:title, "サーバー名を記入してください。「〇〇サーバー運営募集！！」等の文章は、ご控えください)", class: "form-label margin-top-30px", style: "font-size: 18px") %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group padding-top-15">
      <%= f.label :body, "内容(今後、マークダウンでの作成が可能になる予定です)", class: "form-label margin-top-30px", style: "font-size: 18px" %>
      <%= f.text_area :body, rows: 10, id: "editor", class: "form-control", style: "margin-top: 35px;"%>
    </div>
    <%= f.submit "編集して更新する", class: "btn btn-success", style: "margin-top: 35px; margin-bottom: 35px;" %>
<% end %>
</div>

app/views/articles/index.html.erb
<% content_for :title do %>
  MCraft｜募集中のサーバー
<% end %>

<% content_for :css do %>
  <%= stylesheet_link_tag 'articles' %>
<% end %>

<head>
  <style>
      .header {
          background: #a29bfe;
          text-align: center;
      }
      .card {
          min-width: 220px;
          max-width: 270px;
          margin-bottom: 10px !important;
          margin: auto;
      }
      .sidebar {
          min-height: 500px;
      }
  </style>
</head>
<div class="container">
  <div class="row margin-top-bottom-pro">
    <% @article.each do |article| %>
      <div class="col-md-3">
        <div class="card" style="width: 18rem;">
            <%= link_to article do %>
              <div class="card" style="width: 18rem;">
                <% if article.image? %>
                  <%= image_tag article.image.to_s, style: "width: 400px;height: 180px;object-fit: cover;", class: "img-fluid img_radius" %>
                <% else %>
                  <%= image_tag "need/default.png", style: "width: 400px;height: 180px;object-fit: cover;" , class: "img-fluid img_radius" %>
                <% end %>
                <div class="card-body">
                  <h1 class="card-title"><%= article.title %></h1>
                  <p class="card-text">募集開始日: <%= article.created_at.strftime("%Y年%-m月%-d日") %></p>
                  <p class="card-text">いいね数: 0</p>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<% content_for :title do %>
  MCraft｜スタッフを募集する
<% end %>
<div class="container">

  <% if user_signed_in? %>

    <h1 class="text-center margin-top-bottom-form">スタッフを募集する</h1>

    <%= form_for @article do |f| %>
      <% if @article.image? %>
        <%= image_tag @article.image.url %>
      <% else %>
        <%= image_tag "need/default.png", class: "img-fluid"%>
      <% end %>
      <%= f.file_field :image %>
      <p>※選択しても表示されている画像は変わりませんが投稿すると、表示されます。</p>

      <div class="form-group padding-top-15">
        <%= f.label :"サーバー名を記入してください。「〇〇サーバー運営募集！！」等の文章は、ご控えください)", class: "form-label margin-top-30px", style: "font-size: 18px" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group padding-top-15">
        <%= f.label :"募集内容", class: "margin-top-30px", style: "font-size: 18px" %>
        <%= f.text_area :body, rows: 10, id: "editor", class: "form-control", style: "margin-top: 35px;"%>
      </div>
      <%= f.submit "募集を開始する", class: "btn btn-success", style: "margin-top: 35px; margin-bottom: 35px;" %>

    <% end %>
  <% else %>
    <p class="text-center">スタッフを募集するには、ログインしてください</p>
  <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<% content_for :title do %>
  MCraft｜<%= @article.title %>
<% end %>
<% content_for :css do %>
  <%= stylesheet_link_tag 'articles' %>
<% end %>
<head>
  <style>
      .header {
          background: #a29bfe;
          text-align: center;
      }
      .card {
          max-width: 270px;
          min-width: 220px;
          margin-bottom: 10px !important;
          margin: auto;
      }
      .sidebar {
          min-height: 500px;
      }
  </style>
</head>
<div class="container">
  <div class="column">
    <% if @article.image? %>
      <%= image_tag @article.image.url, class: "img-fluid" %>
    <% else %>
      <%= image_tag "need/default.png", class: "img-fluid" %>
    <% end %>
    <h1><strong><%= @article.title %></strong></h1>
      <p style="margin-bottom: 50px">投稿者: <%= @user.name %>
        <%= link_to "" do %>
          <%= image_tag "need/good.png", width:"24px", height:"24px" %> 0</p>
        <% end %>
    <p><%= markdown(@article.body) %></p>
    <% if user_signed_in? && @article.user_id == current_user.id %>
      <%= link_to "編集する", edit_article_path(@article), class: "btn btn-primary", style: "margin-bottom: 100px; margin-top: 30px" %>
      <%= link_to "削除する", article_path(@article), method: :delete, data: {confirm: "削除してもよろしいですか？"}, class: "btn btn-danger", style: "margin-bottom: 100px; margin-top: 30px" %>
    <% end %>

  </div>

</div>