config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  resources :articles
  resources :users

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get "/homes/userule", to: "homes#userule"
  get "/homes/privacy", to: "homes#privacy"
  # get "/profile/index", to: "profile#index"
  # post "articles/:id/update" => "articles#update"
  # get "/articles/new", to: "articles#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield :css %>
    <%= javascript_pack_tag 'application' %>
    <title><%= content_for?(:title) ? yield(:title) : "デフォルトタイトル"%></title>

    <link rel="stylesheet" href="assets/simplemde.min.css">
    <script src="assets/simplemde.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato|Roboto">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <style>
      .text {
        color: gray;
        text-decoration: none;
        transition: 0.2s;
      }
      .text:hover{
          color: black;
      }
      .accountNav {
          text-decoration: none;
          color: black;
          transition: 0.2s;
      }
      .accountNav:hover {
          background-color: #cacaca;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/" style="margin-left: 15px">- MCraft -</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">ホーム</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/articles">スタッフを募集しているサーバー</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users">協力したい人 依頼募集中の人</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users">みんなの作品</a>
          </li>
        </ul>
      </div>
      <div class="d-flex flex-row-reverse bd-highlight">
        <% if user_signed_in? %>
          <p class="navbar-text navbar-right phone-size" style="margin: 18px"><%= link_to "ログアウト", destroy_user_session_path %></p>
          <p class="navbar-text navbar-right phone-size" style="margin: 18px"><%= link_to "スタッフを募集する", new_article_path %></p>
        <% else %>
          <%= link_to new_user_registration_path, class: "accountNav" do %>
            <p class="navbar-text navbar-right phone-size" style="margin: 18px">
              <%= image_tag "accounts/account", width:"32px", height:"32px" %>
              アカウント作成
            </p>
          <% end %>
          <%= link_to new_user_session_path, class:"accountNav" do %>
            <p class="navbar-text navbar-right phone-size" style="margin: 18px">
              <%= image_tag "accounts/login", width:"32px", height:"32px" %>
              ログイン
            </p>
          <% end %>
      <% end %>
      </div>
    </nav>

    <%= yield %>

    <footer class="text-center text-lg-start bg-light text-muted" style="padding: 0px">
      <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <div>
        </div>
      </section>
      <section class="">
        <div class="container">
          <h1 class="fw-bold" style="margin-top: 16px">MCraft</h1>
          <%= link_to "プライバシーポリシー", "/homes/privacy", class: 'text'%><br>
          <%= link_to "利用規約", "/homes/userule", class: "text" %><br>
          <%= link_to "お問い合わせ (TwitterのDMまで)", "https://twitter.com/Mineck100", class:"margin", class: "text" %>
        </div>
      </section>
      <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        Minecraft は Mojang AB の登録商標です。本サービスは、Mojang社から承認されておらず、Mojang社とは関係ありません。<br>
        © 2021 MCraft Copyright:
        <a class="text text-reset fw-bold" href="https://twitter.com/Mineck100" target="_blank" style="margin-bottom: 16px">Mineck/まいんっく</a>
      </div>
    </footer>

    <script>
      // ホバー時のエフェクト
    </script>

  </body>
</html>